ip: "9.40.192.123"
user_name: "root"
password: "********"
prompt: "~]#"
ip_server: "9.40.192.198"
user_name_server: "root"
password_server: "********"
prompt_server: "~]#"
nfs_path: "/home/mnt/testarea/nfs"
